//! GourmelyPrint Bridge — entry point.
//!
//! Wiring:
//!   1. Tauri builds the desktop chrome (window + tray) and registers
//!      auto-start/opener/updater plugins.
//!   2. A tokio task spawned at startup runs the WSS server that the
//!      POS web app connects to. The server stays alive for the entire
//!      app lifetime and shuts down cleanly when the user quits.
//!   3. Each WS message dispatches to the `printer` module which talks
//!      to the Windows print spooler.

pub mod config;
pub mod error;
pub mod printer;
pub mod server;
pub mod tray;

use tauri_plugin_autostart::MacosLauncher;

/// TLS material embedded at compile time so the installer is a single
/// self-contained .exe. The chain is the public Let's Encrypt cert
/// (safe to bundle — it's served on every TLS handshake) plus the
/// private key, which is acceptable to embed because every customer
/// shares the same `localhost.gourmelyhub.busticco.com` cert (the DNS
/// record only resolves to 127.0.0.1, so the attack surface is local).
/// Same security model as QZ Tray's `localhost.qz.io` cert bundling.
const CERT_PEM: &[u8] = include_bytes!("../certs/fullchain.pem");
const KEY_PEM: &[u8] = include_bytes!("../certs/privkey.pem");

/// Tauri command: returns the list of printers registered on this
/// machine. Exposed both to the WSS clients (via `server::handle`) and
/// to the Tauri webview UI (settings page can show what's available).
#[tauri::command]
fn list_printers() -> Result<Vec<String>, String> {
    printer::list().map_err(|e| e.to_string())
}

/// Tauri command: send a test ticket so the operator can verify a
/// printer is alive without going through the POS web.
#[tauri::command]
fn test_print(printer_name: String) -> Result<u32, String> {
    let bytes = printer::test_ticket_bytes();
    printer::print_raw(&printer_name, &bytes).map_err(|e| e.to_string())
}

/// Tauri command: enable or disable auto-start with Windows. Backed by
/// the autostart plugin which writes/removes the HKCU\Run entry.
#[tauri::command]
async fn set_autostart(
    app: tauri::AppHandle,
    enabled: bool,
) -> Result<(), String> {
    use tauri_plugin_autostart::ManagerExt;
    let manager = app.autolaunch();
    if enabled {
        manager.enable().map_err(|e| e.to_string())
    } else {
        manager.disable().map_err(|e| e.to_string())
    }
}

/// Tauri command: read current auto-start status. Used by the settings
/// UI to hydrate the toggle on open.
#[tauri::command]
fn is_autostart_enabled(app: tauri::AppHandle) -> Result<bool, String> {
    use tauri_plugin_autostart::ManagerExt;
    app.autolaunch().is_enabled().map_err(|e| e.to_string())
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| "print_bridge_lib=info,tower_http=info,axum=info".into()),
        )
        .init();

    tracing::info!(
        "GourmelyPrint Bridge starting (v{})",
        env!("CARGO_PKG_VERSION")
    );

    tauri::Builder::default()
        // opener: lets the tray menu open files / URLs without spawning shell commands.
        .plugin(tauri_plugin_opener::init())
        // autostart: HKCU\...\Run on Windows (no-op flag for macOS — not in scope yet).
        .plugin(tauri_plugin_autostart::init(
            MacosLauncher::LaunchAgent,
            None,
        ))
        // updater plugin wiring is in Cargo.toml + lib.rs ready to enable, but
        // we defer the actual `tauri_plugin_updater::Builder::new().build()`
        // registration to Phase 5 because Tauri requires a valid ed25519
        // pubkey in `tauri.conf.json > plugins.updater.pubkey` before it
        // will boot — that keypair is generated by the release pipeline.
        .invoke_handler(tauri::generate_handler![
            list_printers,
            test_print,
            set_autostart,
            is_autostart_enabled,
        ])
        .setup(|app| {
            // Install the system tray icon. Failure here is recoverable
            // (the WSS still works), but log loudly so a regression is
            // obvious in a support log.
            if let Err(e) = tray::install(app.handle()) {
                tracing::error!("failed to install tray icon: {e}");
            }

            // Spawn the server on Tauri's runtime so it shuts down
            // cleanly when the app exits. Certs are embedded into the
            // binary at compile time — no loose PEM files on disk
            // means no permission errors and no support tickets about
            // "I deleted that folder by mistake".
            tauri::async_runtime::spawn(async move {
                if let Err(e) = server::serve(CERT_PEM, KEY_PEM).await {
                    tracing::error!("server exited: {e}");
                }
            });

            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
